/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package canvas.consulta;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import models.Cliente;
import service.ClienteService;

/**
 *
 * @author tailon.prado
 */
public class ConsultaCliente extends javax.swing.JFrame {

    /** Creates new form ConsultaItem */
    public ConsultaCliente() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idCliente = new javax.swing.JTextField();
        cpfCliente = new javax.swing.JTextField();
        nomeCliente = new javax.swing.JTextField();
        consultaCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idClienteKeyReleased(evt);
            }
        });

        cpfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpfClienteKeyReleased(evt);
            }
        });

        consultaCliente.setText("Consultar");
        consultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Id");

        jLabel2.setText("Cpf");

        jLabel3.setText("Nome");

        tableCliente = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tableCliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Id", "Cpf", "Nome",
            }

        ));
        tableCliente.setFocusable(false);
        tableCliente.setShowGrid(false);
        tableCliente.getTableHeader().setResizingAllowed(false);
        tableCliente.getTableHeader().setReorderingAllowed(false);
        TableColumn colIdCliente = tableCliente.getColumnModel().getColumn(0);
        TableColumn colCpfCliente = tableCliente.getColumnModel().getColumn(1);
        TableColumn colNomeCliente = tableCliente.getColumnModel().getColumn(2);

        colIdCliente.setPreferredWidth(50);
        colCpfCliente.setPreferredWidth(150);
        colNomeCliente.setPreferredWidth(450);
        jScrollPane2.setViewportView(tableCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeCliente)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(consultaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(consultaCliente))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idClienteKeyReleased
        idCliente.setText(idCliente.getText().replaceAll("[^0-9]+", ""));
    }//GEN-LAST:event_idClienteKeyReleased

    private void cpfClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfClienteKeyReleased
        cpfCliente.setText(cpfCliente.getText().replaceAll("[^0-9]+", ""));
    }//GEN-LAST:event_cpfClienteKeyReleased

    private void consultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaClienteActionPerformed
        ArrayList<Cliente> clientes = new ArrayList<>();
        ClienteService clienteService = new ClienteService();
        //limpaCliente();
        try {
            clientes = clienteService.findByRel(montaWhere());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao realizar a consulta. Erro: "+ ex.getMessage());
        }
        
        Object[][] obj = new Object[clientes.size()][3];
        
        int linha = 0;
        for (Cliente cliente : clientes) {
            obj[linha][0] = cliente.getId();
            obj[linha][1] = cliente.getCpf();
            obj[linha][2] = cliente.getNome();
            linha++;
        }
        
        tableCliente.setModel(new javax.swing.table.DefaultTableModel(
            obj,
            new String [] {
                "Id", "Cpf", "Nome", 
            }

        ));
        TableColumn colIdCliente = tableCliente.getColumnModel().getColumn(0);
        TableColumn colCpfCliente = tableCliente.getColumnModel().getColumn(1);
        TableColumn colNomeCliente = tableCliente.getColumnModel().getColumn(2);

        colIdCliente.setPreferredWidth(50);
        colCpfCliente.setPreferredWidth(150);
        colNomeCliente.setPreferredWidth(450);
    }//GEN-LAST:event_consultaClienteActionPerformed

    private String montaWhere(){
        String retorno = " where 1 = 1 ";
        if(!(idCliente.getText().equals(""))){
            retorno += " and id = " + idCliente.getText();
        }
        if(!(cpfCliente.getText().equals(""))){
            retorno += " and cpf = '" + cpfCliente.getText() + "' ";
        }
        if(!(nomeCliente.getText().equals(""))){
            retorno += " and upper(nome) like '%" + nomeCliente.getText().toUpperCase() +"%'";
        }
        retorno += " order by id desc ";
        return retorno;
    }
    
    private void limpaCliente(){
        int linha = 0;
        
        while(tableCliente.getValueAt(linha, 0) != null){
            tableCliente.setValueAt("", linha, 0);
            tableCliente.setValueAt("", linha, 1);
            tableCliente.setValueAt("", linha, 2);
            linha++;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultaCliente;
    private javax.swing.JTextField cpfCliente;
    private javax.swing.JTextField idCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomeCliente;
    private javax.swing.JTable tableCliente;
    // End of variables declaration//GEN-END:variables

}
