/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package canvas.consulta;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import models.Item;
import service.ClienteService;
import service.ItemService;

/**
 *
 * @author tailon.prado
 */
public class ConsultaItem extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaCliente
     */
    public ConsultaItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idItem = new javax.swing.JTextField();
        descricaoItem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableItem = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        consultarItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idItemKeyReleased(evt);
            }
        });

        tableItem = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tableItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "id", "descricao", "valor unit.",
            }
        ));
        tableItem.setFocusable(false);
        tableItem.setShowGrid(false);
        TableColumn colIdItem = tableItem.getColumnModel().getColumn(0);
        TableColumn colDescricaoItem = tableItem.getColumnModel().getColumn(1);
        TableColumn colvalorItem = tableItem.getColumnModel().getColumn(2);

        colIdItem.setPreferredWidth(50);
        colDescricaoItem.setPreferredWidth(500);
        colvalorItem.setPreferredWidth(100);
        tableItem.getTableHeader().setResizingAllowed(false);
        tableItem.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableItem);

        jLabel1.setText("Id ");

        jLabel2.setText("Descrição");

        consultarItem.setText("Consultar");
        consultarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(consultarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idItem, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descricaoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descricaoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultarItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idItemKeyReleased
        idItem.setText(idItem.getText().replaceAll("[^0-9]+", ""));
    }//GEN-LAST:event_idItemKeyReleased

    private void consultarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarItemActionPerformed
        ArrayList<Item> itens = new ArrayList<>();
        ItemService itemService = new ItemService();
        
        try {
            itens = itemService.findByRel(montaWhere());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao realizar a consulta. Erro: "+ ex.getMessage());
        }
        
        Object[][] obj = new Object[itens.size()][3];
        
        int linha = 0;
        for (Item item : itens) {
            obj[linha][0] = item.getId();
            obj[linha][1] = item.getDescricao();
            String vlItem = item.getVlItem().toString();
            if(vlItem.contains(".")){
                vlItem += "000";
                vlItem = vlItem.substring(0, vlItem.indexOf(".") +3);
            }
            obj[linha][2] = vlItem;
            linha++;
        }
        
        tableItem.setModel(new javax.swing.table.DefaultTableModel(
            obj,
            new String [] {
                "id", "descricao", "valor unit.", 
            }

        ));
        TableColumn colIdItem = tableItem.getColumnModel().getColumn(0);
        TableColumn colDescricaoItem = tableItem.getColumnModel().getColumn(1);
        TableColumn colvalorItem = tableItem.getColumnModel().getColumn(2);

        colIdItem.setPreferredWidth(50);
        colDescricaoItem.setPreferredWidth(500);
        colvalorItem.setPreferredWidth(100);
    }//GEN-LAST:event_consultarItemActionPerformed

    private String montaWhere(){
        String retorno = " where 1 = 1 ";
        if(!(idItem.getText().equals(""))){
            retorno += " and id = " + idItem.getText();
        }
        if(!(descricaoItem.getText().equals(""))){
            retorno += " and upper(descricao) like '%" + descricaoItem.getText().toUpperCase() +"%'";
        }
        retorno += " order by descricao asc ";
        return retorno;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarItem;
    private javax.swing.JTextField descricaoItem;
    private javax.swing.JTextField idItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableItem;
    // End of variables declaration//GEN-END:variables
}
