/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package canvas.consulta;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import models.ItemVenda;
import models.Venda;
import service.ItemVendaService;
import service.VendaService;

/**
 *
 * @author tailon.prado
 */
public class ConsultaVenda extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaVenda
     */
    public ConsultaVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        idClienteVenda = new javax.swing.JTextField();
        nomeClienteVenda = new javax.swing.JTextField();
        idItemVenda = new javax.swing.JTextField();
        descricaoItemVenda = new javax.swing.JTextField();
        valorInicialVenda = new javax.swing.JTextField();
        valorFinalVEnda = new javax.swing.JTextField();
        consultarVenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableVenda = new javax.swing.JTable();
        ordemVenda = new javax.swing.JComboBox<>();
        tipoOrdencaoVenda = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableItemVenda = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        idVenda = new javax.swing.JTextField();
        cpfCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        jTextField7.setText("jTextField7");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idClienteVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idClienteVendaActionPerformed(evt);
            }
        });
        idClienteVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idClienteVendaKeyReleased(evt);
            }
        });

        idItemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idItemVendaActionPerformed(evt);
            }
        });
        idItemVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idItemVendaKeyReleased(evt);
            }
        });

        valorInicialVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorInicialVendaActionPerformed(evt);
            }
        });
        valorInicialVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorInicialVendaKeyReleased(evt);
            }
        });

        valorFinalVEnda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorFinalVEndaKeyReleased(evt);
            }
        });

        consultarVenda.setText("Consultar");
        consultarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarVendaActionPerformed(evt);
            }
        });

        jLabel1.setText("Id Cliente");

        jLabel2.setText("Nome Cliente");

        jLabel3.setText("Descrição Item");

        jLabel4.setText("Id Item");

        jLabel5.setText("Valor da Venda");

        jLabel6.setText("Até");

        TableVenda = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        TableVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Id Venda", "Id Cliente", "Nome Cliente", "Total Venda"
            }

        ));
        TableVenda.setFocusable(false);
        TableVenda.setName(""); // NOI18N
        TableVenda.setShowGrid(false);
        TableVenda.getTableHeader().setResizingAllowed(false);
        TableVenda.getTableHeader().setReorderingAllowed(false);
        TableColumn colIdCompra = TableVenda.getColumnModel().getColumn(0);
        TableColumn colIdCliente = TableVenda.getColumnModel().getColumn(1);
        TableColumn colNomeCliente = TableVenda.getColumnModel().getColumn(2);
        TableColumn colTotalCompra = TableVenda.getColumnModel().getColumn(3);

        colIdCompra.setPreferredWidth(60);
        colIdCliente.setPreferredWidth(60);
        colNomeCliente.setPreferredWidth(255);
        colTotalCompra.setPreferredWidth(100);
        TableVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableVendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableVenda);

        ordemVenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome Cliente", "Id Venda", "Valor Venda" }));
        ordemVenda.setSelectedIndex(1);
        ordemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordemVendaActionPerformed(evt);
            }
        });

        tipoOrdencaoVenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crescente", "Decrescente" }));
        tipoOrdencaoVenda.setSelectedIndex(1);
        tipoOrdencaoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoOrdencaoVendaActionPerformed(evt);
            }
        });

        jLabel7.setText("Ordenação");

        jLabel8.setText("Tipo de Ordenação");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Itens Da Venda Selecionada");

        tableItemVenda = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tableItemVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Id Item", "Descrição", "Quantidade", "Valor"
            }
        ));
        tableItemVenda.setFocusable(false);
        tableItemVenda.setShowGrid(false);
        tableItemVenda.getTableHeader().setResizingAllowed(false);
        tableItemVenda.getTableHeader().setReorderingAllowed(false);
        tableItemVenda.setToolTipText("");
        TableColumn colId = tableItemVenda.getColumnModel().getColumn(0);
        TableColumn colDescricao = tableItemVenda.getColumnModel().getColumn(1);
        TableColumn colqtde = tableItemVenda.getColumnModel().getColumn(2);
        TableColumn colvalor = tableItemVenda.getColumnModel().getColumn(3);

        colId.setPreferredWidth(60);
        colDescricao.setPreferredWidth(225);
        colqtde.setPreferredWidth(70);
        colvalor.setPreferredWidth(100);
        jScrollPane2.setViewportView(tableItemVenda);

        jLabel10.setText("Id Venda");

        idVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idVendaKeyReleased(evt);
            }
        });

        cpfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpfClienteKeyReleased(evt);
            }
        });

        jLabel11.setText("Cpf Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ordemVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tipoOrdencaoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(consultarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(jLabel10))
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(idVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(idClienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(idItemVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel3)
                                                .addGap(2, 2, 2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(descricaoItemVenda)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(valorInicialVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel6)
                                                        .addGap(5, 5, 5)
                                                        .addComponent(valorFinalVEnda, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nomeClienteVenda))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idClienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeClienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idItemVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descricaoItemVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valorInicialVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorFinalVEnda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(idVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ordemVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoOrdencaoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarVenda))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarVendaActionPerformed
        limpaVenda();
        VendaService vendaService = new VendaService();
        ArrayList<Venda> listaVenda = new ArrayList<>();
        try {
            listaVenda = vendaService.findRel(montaWhere(), montaOrderBy());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao realizar a consulta. Erro: "+ ex.getMessage());
        }
        
        Object[][] obj = new Object[listaVenda.size()][4];
        
        int linha = 0;
        for (Venda venda : listaVenda) {
            
            obj[linha][0] = venda.getId();
            obj[linha][1] = venda.getCliente().getId();
            obj[linha][2] = venda.getCliente().getNome();
            String vlTotal = (venda.getVlTotal()) + "";
            if(vlTotal.contains(".")){
                vlTotal += "000";
                vlTotal = vlTotal.substring(0, vlTotal.indexOf(".") +3);
            }
            obj[linha][3] = vlTotal;
            linha++;
        }
        
        
        TableVenda.setModel(new javax.swing.table.DefaultTableModel(
            obj,
            new String [] {
                "Id Venda", "Id Cliente", "Nome Cliente", "Total Venda"
            }

        ));
        TableColumn colIdCompra = TableVenda.getColumnModel().getColumn(0);
        TableColumn colIdCliente = TableVenda.getColumnModel().getColumn(1);
        TableColumn colNomeCliente = TableVenda.getColumnModel().getColumn(2);
        TableColumn colTotalCompra = TableVenda.getColumnModel().getColumn(3);

        colIdCompra.setPreferredWidth(60);
        colIdCliente.setPreferredWidth(60);
        colNomeCliente.setPreferredWidth(255);
        colTotalCompra.setPreferredWidth(100);
        
    }//GEN-LAST:event_consultarVendaActionPerformed
    private void limpaVenda(){
        limpaItemVenda();
        
        TableVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Id Venda", "Id Cliente", "Nome Cliente", "Total Venda"
            }

        ));
    }
    
    private String montaOrderBy(){
        String retorno = "";
        
        int indiceSelecionado = ordemVenda.getSelectedIndex();
        switch (indiceSelecionado) {
            case 0:
                retorno = " order by cliente.nome ";
                break;
            case 1:
                retorno = " order by venda.id ";
                break;
            case 2:
                retorno = " order by venda.vl_total ";
                break;
        }
        
        if(tipoOrdencaoVenda.getSelectedIndex() == 0)
            retorno +=  " asc ";
        else if(tipoOrdencaoVenda.getSelectedIndex() == 1)
            retorno +=  " desc ";
        
        return retorno;
    }
    
    private String montaWhere(){
        String retorno = "";
        if(!(idClienteVenda.getText().equals(""))){
            retorno += " and cliente.id = " + idClienteVenda.getText();
        }
        if(!(cpfCliente.getText().equals(""))){
            retorno += "and cliente.cpf = '" + cpfCliente.getText() +"' ";
        }
        if(!(idVenda.getText().equals(""))){
            retorno += " and venda.id = " + idVenda.getText();
        }
        if(!(valorInicialVenda.getText().equals(""))){
            retorno += " and venda.vl_total > " + valorInicialVenda.getText();
        }
        if(!(valorFinalVEnda.getText().equals(""))){
            retorno += " and venda.vl_total < " + valorFinalVEnda.getText();
        }
        if(!(nomeClienteVenda.getText().equals(""))){
            retorno += " and upper(cliente.nome) like '%" + nomeClienteVenda.getText().toUpperCase() +"%'";
        }
        
        if(!(descricaoItemVenda.getText().equals(""))){
            retorno += " and exists (select 1 " +
                                      "from itemvenda, " +
                                           "item " +
                                     "where itemvenda.id_venda = venda.id " +
                                       "and itemvenda.id_item  = item.id " +
                                       "and upper(item.descricao) like ('%"+descricaoItemVenda.getText().toUpperCase()+"%'))";
        }
        if(!(idItemVenda.getText().equals(""))){
            retorno += " and exists (select 1 " +
                                      "from itemvenda, " +
                                           "item " +
                                     "where itemvenda.id_venda = venda.id " +
                                       "and itemvenda.id_item  = " + idItemVenda.getText() + " )";
        }
        return retorno;
    }
    private void ordemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordemVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordemVendaActionPerformed

    private void tipoOrdencaoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoOrdencaoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoOrdencaoVendaActionPerformed

    private void valorInicialVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorInicialVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorInicialVendaActionPerformed

    private void idItemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idItemVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idItemVendaActionPerformed

    private void idClienteVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idClienteVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idClienteVendaActionPerformed

    private void valorInicialVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorInicialVendaKeyReleased
        if(evt.getKeyCode() != 44)
            if(evt.getKeyCode() != 110)
                if(evt.getKeyCode() != 46)
                    valorInicialVenda.setText(valorInicialVenda.getText().replaceAll("[^0-9.]+", ""));
        if(valorInicialVenda.getText().contains(",")||valorInicialVenda.getText().contains(".")){
            String var = (valorInicialVenda.getText().replaceAll("[^,.]+", ""));
            if(var.length() > 1)
                valorInicialVenda.setText(valorInicialVenda.getText().substring(0, valorInicialVenda.getText().length()-1));
        }
        valorInicialVenda.setText(valorInicialVenda.getText().replaceAll("[,]+", "."));
    }//GEN-LAST:event_valorInicialVendaKeyReleased

    private void valorFinalVEndaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorFinalVEndaKeyReleased
        if(evt.getKeyCode() != 44)
            if(evt.getKeyCode() != 110)
                if(evt.getKeyCode() != 46)
                    valorFinalVEnda.setText(valorFinalVEnda.getText().replaceAll("[^0-9.]+", ""));
        if(valorFinalVEnda.getText().contains(",")||valorFinalVEnda.getText().contains(".")){
            String var = (valorFinalVEnda.getText().replaceAll("[^,.]+", ""));
            if(var.length() > 1)
                valorFinalVEnda.setText(valorFinalVEnda.getText().substring(0, valorFinalVEnda.getText().length()-1));
        }
        valorFinalVEnda.setText(valorFinalVEnda.getText().replaceAll("[,]+", "."));
    }//GEN-LAST:event_valorFinalVEndaKeyReleased

    private void idItemVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idItemVendaKeyReleased
        idItemVenda.setText(idItemVenda.getText().replaceAll("[^0-9]+", ""));            
    }//GEN-LAST:event_idItemVendaKeyReleased

    private void idClienteVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idClienteVendaKeyReleased
        idClienteVenda.setText(idClienteVenda.getText().replaceAll("[^0-9]+", ""));
    }//GEN-LAST:event_idClienteVendaKeyReleased

    private void idVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idVendaKeyReleased
        idVenda.setText(idVenda.getText().replaceAll("[^0-9]+", ""));            
    }//GEN-LAST:event_idVendaKeyReleased

    private void cpfClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfClienteKeyReleased
        cpfCliente.setText(cpfCliente.getText().replaceAll("[^0-9]+", ""));            
    }//GEN-LAST:event_cpfClienteKeyReleased

    private void TableVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableVendaMouseClicked
        try {
            Thread.sleep(5);
        } catch (InterruptedException ex) {
            Logger.getLogger(ConsultaVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        executaCosnultaGridInferior();
        
    }//GEN-LAST:event_TableVendaMouseClicked

    private void executaCosnultaGridInferior(){
        
        limpaItemVenda();
        
        String idVenda = (TableVenda.getValueAt(TableVenda.getSelectedRow(), 0)).toString();
        ArrayList<ItemVenda> listaItemVenda = new ArrayList<>();
        
        if(!(idVenda.equals(""))){
            ItemVendaService itemVendaService = new ItemVendaService();
            try {
                listaItemVenda  = itemVendaService.findByVenda(Integer.parseInt(idVenda));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro ao realizar a consulta dos itens da compra ("+idVenda+"). Erro: " + ex.getMessage());
            }
        }
        
        Object[][] obj = new Object[listaItemVenda.size()][4];
        int linha = 0;
        
        for (ItemVenda itemVenda : listaItemVenda) {
            obj[linha][0] = itemVenda.getItem().getId();
            obj[linha][1] = itemVenda.getItem().getDescricao();
            obj[linha][2] = itemVenda.getQtde();
            String vlTotal = (itemVenda.getQtde() * itemVenda.getItem().getVlItem()) + "";
            if(vlTotal.contains(".")){
                vlTotal += "000";
                vlTotal = vlTotal.substring(0, vlTotal.indexOf(".") +3);
            }
            obj[linha][3] = vlTotal;
            linha++;
        }
        
        tableItemVenda.setModel(new javax.swing.table.DefaultTableModel(
            obj,
            new String [] {
                "Id Item", "Descrição", "Quantidade", "Valor"
            }
        ));
        
        TableColumn colId = tableItemVenda.getColumnModel().getColumn(0);
        TableColumn colDescricao = tableItemVenda.getColumnModel().getColumn(1);
        TableColumn colqtde = tableItemVenda.getColumnModel().getColumn(2);
        TableColumn colvalor = tableItemVenda.getColumnModel().getColumn(3);

        colId.setPreferredWidth(60);
        colDescricao.setPreferredWidth(225);
        colqtde.setPreferredWidth(70);
        colvalor.setPreferredWidth(100);

    }
    private void limpaItemVenda(){
        tableItemVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Id Item", "Descrição", "Quantidade", "Valor"
            }
        ));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TableVenda;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton consultarVenda;
    private javax.swing.JTextField cpfCliente;
    private javax.swing.JTextField descricaoItemVenda;
    private javax.swing.JTextField idClienteVenda;
    private javax.swing.JTextField idItemVenda;
    private javax.swing.JTextField idVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField nomeClienteVenda;
    private javax.swing.JComboBox<String> ordemVenda;
    public javax.swing.JTable tableItemVenda;
    private javax.swing.JComboBox<String> tipoOrdencaoVenda;
    private javax.swing.JTextField valorFinalVEnda;
    private javax.swing.JTextField valorInicialVenda;
    // End of variables declaration//GEN-END:variables
}
