/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package canvas.cadastro;

import Exception.DescricaoInvalidaException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import models.Cliente;
import models.Item;
import service.ClienteService;
import service.ItemService;

/**
 *
 * @author tailon.prado
 */
public class CadastroItem extends javax.swing.JFrame {

    /**
     * Creates new form CadastroItem
     */
    public CadastroItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        atualizaCliente = new javax.swing.JButton();
        excluiCliente = new javax.swing.JButton();
        idCliente = new javax.swing.JTextField();
        nomeCliente = new javax.swing.JTextField();
        cpfCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        atualizaItem = new javax.swing.JButton();
        excluiItem = new javax.swing.JButton();
        idItem = new javax.swing.JTextField();
        valorItem = new javax.swing.JTextField();
        descricaoItem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        atualizaCliente.setText("Salvar");

        excluiCliente.setText("Excluir");
        excluiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluiClienteActionPerformed(evt);
            }
        });

        idCliente.setText("jTextField1");

        nomeCliente.setText("jTextField2");

        cpfCliente.setText("jTextField3");

        jLabel1.setText("Id");

        jLabel2.setText("Cpf");

        jLabel3.setText("Nome");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(excluiCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(atualizaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpfCliente)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atualizaCliente)
                    .addComponent(excluiCliente))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        atualizaItem.setText("Cadastrar");
        atualizaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaItemActionPerformed(evt);
            }
        });

        excluiItem.setText("Excluir");
        excluiItem.setEnabled(false);
        excluiItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluiItemMouseClicked(evt);
            }
        });
        excluiItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluiItemActionPerformed(evt);
            }
        });

        idItem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idItemFocusLost(evt);
            }
        });
        idItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idItemActionPerformed(evt);
            }
        });
        idItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idItemKeyReleased(evt);
            }
        });

        valorItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorItemActionPerformed(evt);
            }
        });
        valorItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorItemKeyReleased(evt);
            }
        });

        descricaoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoItemActionPerformed(evt);
            }
        });

        jLabel4.setText("Id");

        jLabel5.setText("Descrição");

        jLabel6.setText("Valor unit.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(excluiItem, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atualizaItem, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(idItem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descricaoItem)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descricaoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizaItem)
                    .addComponent(excluiItem))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluiClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluiClienteActionPerformed

    private void excluiItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluiItemActionPerformed
        Item item = new Item();
        item.setId(Integer.parseInt(idItem.getText()));
        item.setDescricao(descricaoItem.getText());
        item.setVlItem(Double.parseDouble(valorItem.getText()));
        ItemService itemService = new ItemService();
        
        try {
            Object[] options = { "Sim", "Não" }; 
            int opcao = JOptionPane.showOptionDialog(null, "Deseja realmente excluir este registro?", "Exclusão de Registro", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]); 
            if (opcao == 0) {
                itemService.delete(item);
                JOptionPane.showMessageDialog(null, "Item ("+item.getId()+") excluido com sucesso");
                idItem.setText("");
                descricaoItem.setText("");
                valorItem.setText("");
                excluiItem.setEnabled(false);
                atualizaItem.setText("Cadastrar");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao excluir Item. Erro: " + ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir Item. Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_excluiItemActionPerformed

    private void descricaoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoItemActionPerformed

    private void valorItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorItemActionPerformed

    private void idItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idItemActionPerformed

    private void idItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idItemKeyReleased
        idItem.setText(idItem.getText().replaceAll("[^0-9]+", ""));
    }//GEN-LAST:event_idItemKeyReleased

    private void valorItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorItemKeyReleased
        if(evt.getKeyCode() != 44)
            if(evt.getKeyCode() != 110)
                if(evt.getKeyCode() != 46)
                    valorItem.setText(valorItem.getText().replaceAll("[^0-9.]+", ""));
        if(valorItem.getText().contains(",")||valorItem.getText().contains(".")){
            String var = (valorItem.getText().replaceAll("[^,.]+", ""));
            if(var.length() > 1)
                valorItem.setText(valorItem.getText().substring(0, valorItem.getText().length()-1));
        }
        valorItem.setText(valorItem.getText().replaceAll("[,]+", "."));
    }//GEN-LAST:event_valorItemKeyReleased

    private void idItemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idItemFocusLost
        if(idItem.getText().equals("")){
            excluiItem.setEnabled(false);
            atualizaItem.setText("Cadastrar");
        }else{
            excluiItem.setEnabled(true);
            atualizaItem.setText("Atualizar");
            
            ItemService itemService = new ItemService();
            Item item = new Item();
            try {
                item = itemService.findById(Integer.parseInt(idItem.getText()));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro ao buscar o item. Erro: "+ex.getMessage());
            }
            
            if(item.getId() == null){
                JOptionPane.showMessageDialog(null, "Item com id ("+idItem.getText()+") não encontrado.");
                excluiItem.setEnabled(false);
                atualizaItem.setText("Cadastrar");
                idItem.setText("");
            }else{
                descricaoItem.setText(item.getDescricao());
                valorItem.setText(item.getVlItem().toString());
            }
        }
    }//GEN-LAST:event_idItemFocusLost

    private void atualizaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaItemActionPerformed
        Item item = new Item();
        if(!idItem.getText().equals(""))
            item.setId(Integer.parseInt(idItem.getText()));
        item.setDescricao(descricaoItem.getText());
        if(!valorItem.getText().equals(""))
            item.setVlItem(Double.parseDouble(valorItem.getText()));
        
        ItemService itemService = new ItemService();
        if(idItem.getText().equals("")){
            try {   
                itemService.insert(item);
                idItem.setText(item.getId().toString());
                excluiItem.setEnabled(true);
                atualizaItem.setText("Atualizar");
                JOptionPane.showMessageDialog(null, "Item ("+item.getId()+") cadastrado com sucesso.");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar item. Erro: "+ex.getMessage());
            }
        }
        else{
            try {
                itemService.update(item);
                JOptionPane.showMessageDialog(null, "Cliente ("+item.getId()+") atualizado com sucesso.");
            } catch (DescricaoInvalidaException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao atualizar item. Erro: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_atualizaItemActionPerformed

    private void excluiItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluiItemMouseClicked
    }//GEN-LAST:event_excluiItemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizaCliente;
    private javax.swing.JButton atualizaItem;
    private javax.swing.JTextField cpfCliente;
    private javax.swing.JTextField descricaoItem;
    private javax.swing.JButton excluiCliente;
    private javax.swing.JButton excluiItem;
    private javax.swing.JTextField idCliente;
    private javax.swing.JTextField idItem;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nomeCliente;
    private javax.swing.JTextField valorItem;
    // End of variables declaration//GEN-END:variables
}
